version: 0.0.1.{build}

shallow_clone: true

image: Visual Studio 2017

cache:
  - "%APPDATA%\\stack"

build_script:
  - choco install haskell-stack
  - stack --no-terminal setup > NUL
  - stack --no-terminal exec pacman -- -Syu --force --noconfirm --noprogressbar
  - stack --no-terminal exec pacman -- -Syu --force --noconfirm --noprogressbar
  - stack --no-terminal exec pacman -- -S mingw-w64-x86_64-cmake --force --needed --noconfirm --noprogressbar
  - stack --no-terminal test --haddock

test: off
