name: direct-rocksdb
version: 0.0.2
category: Database
synopsis: Bindings to RocksDB.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/direct-rocksdb

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - rocksdb-5.8/**/**

custom-setup:
  dependencies:
    - base >= 4.10 && < 5
    - Cabal >= 2.0 && < 2.2
    - cabal-toolkit >= 0.0.3
    - directory
    - filepath

ghc-options: -Wall

extra-libraries: stdc++

when:
  - condition: os(windows)
    extra-libraries:
      - rpcrt4

dependencies:
  - base >= 4.10 && < 5
  - bytestring
  - data-default-class
  - safe-exceptions

library:
  source-dirs: src
  other-extensions:
    - DeriveAnyClass
    - RecordWildCards
    - TypeFamilies

tests:
  direct-rocksdb-test:
    source-dirs: test
    main: direct-rocksdb-test.hs
    ghc-options: -threaded -with-rtsopts=-N
    dependencies:
      - direct-rocksdb
