version: 2
jobs:
  build:
    docker:
      - image: terrorjack/rakuen:nightly-2017-11-08
    environment:
      - NINJA_J: 2
    steps:
      - checkout
      - run: stack --no-terminal test --haddock
